name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the graph
        uses: Platane/snk@v3
        with:
          github_user_name: Realpusing
          outputs: |
            ./output/pacman.svg

      - name: Push the output to the 'output' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: output
