name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # setiap hari tengah malam UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: Realpusing
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output # harus sesuai dengan tempat output kamu
          folder: output
